version: '3'
services:
  jhipsterelasticsearchsampleapplication-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
    # volumes:
    #   - ~/volumes/jhipster/jhipsterElasticsearchSampleApplication/elasticsearch/:/usr/share/elasticsearch/data/
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 127.0.0.1:9200:9200
      - 127.0.0.1:9300:9300
    environment:
      - 'xpack.security.enabled=false'
      - 'discovery.type=single-node'
      - 'bootstrap.memory_lock=true'
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
  mysqldb:
    container_name: mysqldb
    image: mysql:5.7
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: my_portal
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
  knowledge:
    links:
      - redis-server
    image: knowledge
    depends_on:
     - mysqldb
    build: .
    environment:
      DATABASE_HOST: mysqldb
      DATABASE_USER: root
      DATABASE_PASSWORD: root
      DATABASE_NAME: my_portal  
      DATABASE_PORT: 3306
    ports:
      - 8080:8080 
  redis-server:
    hostname: redis
    image: 'redis:latest'
    ports:
      - "6379:6379"

volumes:
  db_data: {}
