logging:
  file:
    name: logs/project_log.log
server:
  port: 8080
  servlet:
    context-path: '/api/knowledge/v1'
    encoding:
      charset: 'UTF-8'
      enabled: true
      force: true
spring:
  datasource:
    username: ENC(3nR++9G/RAPIaqtG7PfnOnr306+w0SCy)
    password: ENC(ere/u4lN/PabfbV66AZ7CBW1RlQG476yHSTA2rS+X30=)
    url: ENC(XjqDGvO0BWg6aI7DEXnvOp5QpVnXGvcVqkLNdvLviXgDuEUUSOyELf4sMjE0FR8PbVAT+bN4jMk=)
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: 'update'
  properties:
    hibernate.search.indexing_strategy: manual
    hibernate.search.default.directory_provider: filesystem
    hibernate.search.default.indexBase: 'indexes'
    hibernate.search.default.indexmanager: near-real-time
  messages:
    encoding: 'UTF-8'
    use-code-as-default-message: true
    basename: 'i18n/messages' 
    cache-duration: 60    # 60 second, see the ISO 8601 standard
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.xml
  redis:
    host: 127.0.0.1
    port: 6379

scheduling:
  cache:
    cron: '0 */5 * * * *' # cứ 5 phut chạy 1 lần

jasypt:
  encryptor:
    password: 'YWF9tWp3MYI6lg2imQ/UokKYoIU1Vy/7sqlr+7CToYlGFb7iESOJqKeNfSlHm/qVxVAFeIiB5oMg/f27btXj517Y43FYhiQEWyas540IknRePl1YG2a53FwYQ4UQzQpZ/NM0QHaIJus7huJF+jM6u2v5sn5nwNiyjx7ZWD2AMyZx5hkPjcTT/hDEFC+SrnHp8F1goFLobUYmila8d0mw51un2iNxV+3Q9f8eckBBl7S3eOI1ndQNFm80Puw7QtEJes0JakaFTWkCXpfVLVqW7qyKcy6uWX25fyqqz+tk8Amkr3G59GXm5Cs+HA2DEorReNyMEJ8GNzlHABEIKHR/iw=='
    algorithm: 'PBEWithMD5AndTripleDES'
    pool-size: 4
    key-obtention-iterations: 1500
    provider-name: 'SunJCE'
    salt-generator-classname: 'org.jasypt.salt.RandomSaltGenerator'
    iv-generator-classname: 'org.jasypt.iv.RandomIvGenerator'
    string-output-type: 'base64'
validation:
  phone-number-regex: '^((\s){0,}(0)(3|8|9))(\d{8}(\s){0,})$' #SĐT 10 kí tự, bắt đầu bằng 03 hoặc 08 hoặc 09

rsa:
  key-length: 2048
  algorithm: RSA/ECB/PKCS1Padding
  private-key: 'MIIEowIBAAKCAQEAmD9evqQe1hTXdRPEJKEgkTfPGYBk0c6JCY+vLn1m4pIaaDZdJmEWrug7YwRFGfE9TMKk26M3ACGOiu7Uw267Y85/Lb3maD7CplVkhjXVVcQ8aUI4t6/BFI7wLzt7DqAmlJR4FDgTDFQl1W8ZU+QpPyP8S34s9b+yvJZAPin9Pdd23uqNtBY2RFwu+QS27Q5u6IcCLFsb1wgTb3fq/umiQ4MXRzy6jsHoUQ1Z8n305oUWsxsaC6SLCJsFSJh2w6wakScGAF9hmWdGI+PkodILxhi53zM5gWFzusasW4QQJC7tElwhn4iIcJdYF1OIAhV0RQAxjfb5kZ3/1Dm7GxBYMwIDAQABAoIBADKBiz+5GFWysksvlHkGTtR97CEsm8WSO5nFZbsJdNEi4MnDhyFNQgYiGllduELD6a8GP0Rxn7RWbYAffMucd2PDxCL7hWz9rPsbBu8S+sOqBtRwWHpvPqFATeONWuReMo5FtpQWihMj8y0b3w4aeahtmqu8ntOjlXrEaWl16oHR7pa7pjYL+bHjDSModUlFSz8odOlBYOzCEO8lB4E0xbbinMxGDQ2i/ZMLrZm9yKrqz3jVLfHdEbz4v0nEcWAUJ281ZcBgJHJXpUu/66ntmGmhYSXXhloaVw7PlYw23JQfYEEtlZqujqbaILZWVNM10d7zXnL+VhRLp9mUZxIKWSECgYEAzI4WzpUaLAftjHc1qRDvQl6o42clEPgR4Agx6ulQaeVFEB3Jd+chI2XTxJl9+NoWFpGhBhLoYAuKIa2FXD8T1LmjNkzHtjWbGYia6xgCPwx3bZeNda9/jVfAbNRUNZDN6XVQBBpHM+3NcBSb66wv36qd1oxD646Z736sxfcMJ8MCgYEAvomOZH4Wwq5bsEUB7bqmgnSO9MW5zW1tahV/H/rju7XbKz3nuRFX5C5W4ju/EHJFE7R625esc/gsc4Z+v7P+o3Xj9F8bsVefAniU5R9NzMH+JXeHSfoG6Ca6mfZcjdmeBxSfzL2w2Ntf4K5cV0HQFxWbS2yPWiQzbtBcWsPwdtECgYEAtJ/rR7OljqfZfSVuvsFzZDnODC9yLY+/yQGzgmlPVpLa7yY+VqBDRMyPuJSJBgsdYgRqGcDsbJMEAEUG87PHQRpDIpmd6ClhsaRMl7d1lFLfymf+w6KakSahhfff/ATHrpSmeVjy8snTlFq+a9Z515kDEwZ8my4qg65pxc0mcJ0CgYA2iF4lquTOwWJil82Ogb5IVh3YNoMQJYKMOyzQNVlajxj0Tlp04F7cYtrhEyKDDYFxu1TyZn2oD16BjfvW2ChIFmSwu0vMvPw4k9Rho0z8DoWzqXsiFBpH9VWw3Q7uVlthQWjfC2eDGX5eaujo3GA3SyrQMnjw3q2NyLq2C6BWEQKBgHtkq7CBhIdaSk/bY9xsdKqWAHO3z0EPPjy4JPE6+MLA4vPSG7I9vq6Wlebwag8bfXETyv3geJJ9CjP8JOBqmLIKPRBiXrXJe6LpQ4Jso1+cd9LXxRNhkRf9DwtAaijYm1gkKdM7CAHLyfknn1vMzcGK82v2BOavyFC45z/QjllL'
  public-key: 'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAmD9evqQe1hTXdRPEJKEgkTfPGYBk0c6JCY+vLn1m4pIaaDZdJmEWrug7YwRFGfE9TMKk26M3ACGOiu7Uw267Y85/Lb3maD7CplVkhjXVVcQ8aUI4t6/BFI7wLzt7DqAmlJR4FDgTDFQl1W8ZU+QpPyP8S34s9b+yvJZAPin9Pdd23uqNtBY2RFwu+QS27Q5u6IcCLFsb1wgTb3fq/umiQ4MXRzy6jsHoUQ1Z8n305oUWsxsaC6SLCJsFSJh2w6wakScGAF9hmWdGI+PkodILxhi53zM5gWFzusasW4QQJC7tElwhn4iIcJdYF1OIAhV0RQAxjfb5kZ3/1Dm7GxBYMwIDAQAB'
cache:
  time-to-live:
    token: 60 #giay
security:
  authentication:
    jwt:
      secret-key: aPdSgVkYp3s6v9y$B?E(H+MbQeThWmZq4t7w!z%C*F)J@NcRfUjXn2r5u8x/A?D(
  
  
  
  
  
  
  